name: Animated Custom Sprites CI Deploy

on:
  push:
    branches: ["*"]
    paths: ["AnimatedCustomSprites/**"]
  pull_request_target:
    paths: ["AnimatedCustomSprites/**"]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build_plugin_ci.yml
    with:
      plugin_name: AnimatedCustomSprites
      plugin_path: AnimatedCustomSprites
      tag_prefix: ACS
      release_name_prefix: "Animated Custom Sprites"
      artifact_name_prefix: acs
      include_cwl: true
      prerelease: false