name: Custom Whatever Loader CI Deploy

on:
  push:
    branches: ["*"]
    paths: ["CustomWhateverLoader/**"]
  pull_request_target:
    paths: ["CustomWhateverLoader/**"]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build_plugin_ci.yml
    with:
      plugin_name: CustomWhateverLoader
      plugin_path: CustomWhateverLoader
      tag_prefix: CWL
      release_name_prefix: "Custom Whatever Loader"
      artifact_name_prefix: cwl
      include_cwl: false
      prerelease: false