name: Emmersive Elin CI Deploy

on:
  push:
    branches: ["*"]
    paths: ["Emmersive/**"]
  pull_request_target:
    paths: ["Emmersive/**"]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/build_plugin_ci.yml
    secrets: inherit
    with:
      plugin_name: Emmersive
      plugin_path: Emmersive
      tag_prefix: EM
      release_name_prefix: "Emmersive - Elin with AI"
      artifact_name_prefix: emmersive
      include_cwl: false
      prerelease: false