name: Expanded Moongate Elin CI Deploy

on:
  push:
    branches: ["*"]
    paths: ["ExpandedMoongate/ExpandedMoongate/**"]
  pull_request_target:
    paths: ["ExpandedMoongate/ExpandedMoongate/**"]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/build_plugin_ci.yml
    with:
      plugin_name: ExpandedMoongate
      plugin_path: ExpandedMoongate/ExpandedMoongate
      tag_prefix: EXM
      release_name_prefix: "Expanded Moongate"
      artifact_name_prefix: exmoongate
      include_cwl: true
      prerelease: false